# Build Docker container

name: Container Build

on:
  workflow_dispatch:
    inputs:
      runner_version:
        description: 'Runner version'
        required: true
        default: '2.283.3'

env:
  CONTAINER_REPO: ghcr.io/colindembovsky
  #GH_RUNNER_VERSION: 2.283.3
  #GH_RUNNER_VERSION: 2.279.0

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        os:
        - centos
        - ubuntu

    env:
      CONTAINER_TAG: ${{ matrix.os }}-actions-runner:${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get creation time
        id: time
        uses: actions/github-script@v2
        with:
          script: |
            core.setOutput('datetime', new Date().toISOString());
                    
      - name: Build Container
        run: |
          docker build -f ${{ matrix.os }}-actions-runner/Dockerfile -t ${CONTAINER_REPO}/${CONTAINER_TAG} \
            --build-arg COMMIT_SHA=${{ github.sha }} \
            --build-arg CREATED="${{ steps.time.outputs.datetime }}" \
            --build-arg GH_RUNNER_VERSION="${{ github.events.input.runner_version }}" \
            .
      
      - name: Publish
        run: |
          echo ${{ secrets.CONTAINER_REGISTRY_PAT }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          docker push ${CONTAINER_REPO}/${CONTAINER_TAG}
